name: Node.js CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

  print-secret:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: |
          echo "Secret: ${{ secrets.CANTEST }}" | sed 's/./& /g'